# Copyright (c) 2012-2019 Robin Degen

if (NOT AEON_ARCHITECTURE_SUFFIX_SET)
    if (CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(STATUS "Detected 64-bit compilation.")
        set(AEON_ARCHITECTURE_SUFFIX "64")
        set(AEON_ARCHITECTURE_SUFFIX_SET 1)
        set(AEON_ARCHITECTURE_32_BIT 0)
        set(AEON_ARCHITECTURE_64_BIT 1)
    else ()
        message(STATUS "Detected 32-bit compilation.")
        set(AEON_ARCHITECTURE_SUFFIX "")
        set(AEON_ARCHITECTURE_SUFFIX_SET 1)
        set(AEON_ARCHITECTURE_32_BIT 1)
        set(AEON_ARCHITECTURE_64_BIT 0)
    endif ()
endif ()
