name: Build Conan Package (Windows)

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of the package to build'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Conan install
        run: python -m pip install conan

      - name: Conan detect
        run: conan profile detect

      - uses: actions/checkout@v3.5.3
        with:
          submodules: recursive

      - name: Conan remote
        run: conan config install ./Conan/remotes.json

      - name: Conan login
        env:
          aleya_thirdparty_conan: ${{ secrets.ALEYA_THIRDPARTY_CONAN }}
        run: conan remote login -p $Env:aleya_thirdparty_conan aleya-thirdparty-conan admin

      - name: Conan build msvc2022_x86_64_debug
        run: conan create ./Conan/thirdparty/${{ github.event.inputs.package_name }} -pr ./Conan/profiles/windows/msvc2022_x86_64_debug

      - name: Conan build msvc2022_x86_64_release
        run: conan create ./Conan/thirdparty/${{ github.event.inputs.package_name }} -pr ./Conan/profiles/windows/msvc2022_x86_64_release

      - name: Conan upload
        run: conan upload ${{ github.event.inputs.package_name }} --remote aleya-thirdparty-conan
